/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SiteVitrineRouteImport } from './routes/site-vitrine'
import { Route as SiteInternetSerrurierRouteImport } from './routes/site-internet-serrurier'
import { Route as SiteInternetPlombierRouteImport } from './routes/site-internet-plombier'
import { Route as SiteInternetPeintreRouteImport } from './routes/site-internet-peintre'
import { Route as SiteInternetPaysagisteRouteImport } from './routes/site-internet-paysagiste'
import { Route as SiteInternetMenuisierRouteImport } from './routes/site-internet-menuisier'
import { Route as SiteInternetMaconRouteImport } from './routes/site-internet-macon'
import { Route as SiteInternetElectricienRouteImport } from './routes/site-internet-electricien'
import { Route as SiteInternetCouvreurRouteImport } from './routes/site-internet-couvreur'
import { Route as SiteInternetChauffagisteRouteImport } from './routes/site-internet-chauffagiste'
import { Route as SiteInternetCarreleurRouteImport } from './routes/site-internet-carreleur'
import { Route as SiteEvenementielRouteImport } from './routes/site-evenementiel'
import { Route as SiteECommerceRouteImport } from './routes/site-e-commerce'
import { Route as RefonteSiteInternetRouteImport } from './routes/refonte-site-internet'
import { Route as ReferencementNaturelRouteImport } from './routes/referencement-naturel'
import { Route as ReferencementLocalRouteImport } from './routes/referencement-local'
import { Route as ReferencementIaRouteImport } from './routes/referencement-ia'
import { Route as PubliciteReseauxSociauxRouteImport } from './routes/publicite-reseaux-sociaux'
import { Route as PolitiqueConfidentialiteRouteImport } from './routes/politique-confidentialite'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as LogicielMetierRouteImport } from './routes/logiciel-metier'
import { Route as LandingPageRouteImport } from './routes/landing-page'
import { Route as IntegrationApiRouteImport } from './routes/integration-api'
import { Route as CrmSurMesureRouteImport } from './routes/crm-sur-mesure'
import { Route as CreationSiteInternetRouteImport } from './routes/creation-site-internet'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AutomatisationTachesRouteImport } from './routes/automatisation-taches'
import { Route as ApplicationWebMobileRouteImport } from './routes/application-web-mobile'
import { Route as AgentsIaRouteImport } from './routes/agents-ia'
import { Route as AcquisitionRouteImport } from './routes/acquisition'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RealisationsIndexRouteImport } from './routes/realisations.index'
import { Route as OutilsIndexRouteImport } from './routes/outils.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as RealisationsSlugRouteImport } from './routes/realisations.$slug'
import { Route as OutilsBudgetGoogleAdsArtisanRouteImport } from './routes/outils.budget-google-ads-artisan'
import { Route as OutilsAuditFicheGoogleRouteImport } from './routes/outils.audit-fiche-google'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteVitrineRoute = SiteVitrineRouteImport.update({
  id: '/site-vitrine',
  path: '/site-vitrine',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteInternetSerrurierRoute = SiteInternetSerrurierRouteImport.update({
  id: '/site-internet-serrurier',
  path: '/site-internet-serrurier',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteInternetPlombierRoute = SiteInternetPlombierRouteImport.update({
  id: '/site-internet-plombier',
  path: '/site-internet-plombier',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteInternetPeintreRoute = SiteInternetPeintreRouteImport.update({
  id: '/site-internet-peintre',
  path: '/site-internet-peintre',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteInternetPaysagisteRoute = SiteInternetPaysagisteRouteImport.update({
  id: '/site-internet-paysagiste',
  path: '/site-internet-paysagiste',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteInternetMenuisierRoute = SiteInternetMenuisierRouteImport.update({
  id: '/site-internet-menuisier',
  path: '/site-internet-menuisier',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteInternetMaconRoute = SiteInternetMaconRouteImport.update({
  id: '/site-internet-macon',
  path: '/site-internet-macon',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteInternetElectricienRoute = SiteInternetElectricienRouteImport.update({
  id: '/site-internet-electricien',
  path: '/site-internet-electricien',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteInternetCouvreurRoute = SiteInternetCouvreurRouteImport.update({
  id: '/site-internet-couvreur',
  path: '/site-internet-couvreur',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteInternetChauffagisteRoute =
  SiteInternetChauffagisteRouteImport.update({
    id: '/site-internet-chauffagiste',
    path: '/site-internet-chauffagiste',
    getParentRoute: () => rootRouteImport,
  } as any)
const SiteInternetCarreleurRoute = SiteInternetCarreleurRouteImport.update({
  id: '/site-internet-carreleur',
  path: '/site-internet-carreleur',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteEvenementielRoute = SiteEvenementielRouteImport.update({
  id: '/site-evenementiel',
  path: '/site-evenementiel',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteECommerceRoute = SiteECommerceRouteImport.update({
  id: '/site-e-commerce',
  path: '/site-e-commerce',
  getParentRoute: () => rootRouteImport,
} as any)
const RefonteSiteInternetRoute = RefonteSiteInternetRouteImport.update({
  id: '/refonte-site-internet',
  path: '/refonte-site-internet',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencementNaturelRoute = ReferencementNaturelRouteImport.update({
  id: '/referencement-naturel',
  path: '/referencement-naturel',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencementLocalRoute = ReferencementLocalRouteImport.update({
  id: '/referencement-local',
  path: '/referencement-local',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencementIaRoute = ReferencementIaRouteImport.update({
  id: '/referencement-ia',
  path: '/referencement-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const PubliciteReseauxSociauxRoute = PubliciteReseauxSociauxRouteImport.update({
  id: '/publicite-reseaux-sociaux',
  path: '/publicite-reseaux-sociaux',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueConfidentialiteRoute =
  PolitiqueConfidentialiteRouteImport.update({
    id: '/politique-confidentialite',
    path: '/politique-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const LogicielMetierRoute = LogicielMetierRouteImport.update({
  id: '/logiciel-metier',
  path: '/logiciel-metier',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingPageRoute = LandingPageRouteImport.update({
  id: '/landing-page',
  path: '/landing-page',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationApiRoute = IntegrationApiRouteImport.update({
  id: '/integration-api',
  path: '/integration-api',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmSurMesureRoute = CrmSurMesureRouteImport.update({
  id: '/crm-sur-mesure',
  path: '/crm-sur-mesure',
  getParentRoute: () => rootRouteImport,
} as any)
const CreationSiteInternetRoute = CreationSiteInternetRouteImport.update({
  id: '/creation-site-internet',
  path: '/creation-site-internet',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomatisationTachesRoute = AutomatisationTachesRouteImport.update({
  id: '/automatisation-taches',
  path: '/automatisation-taches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationWebMobileRoute = ApplicationWebMobileRouteImport.update({
  id: '/application-web-mobile',
  path: '/application-web-mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIaRoute = AgentsIaRouteImport.update({
  id: '/agents-ia',
  path: '/agents-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const AcquisitionRoute = AcquisitionRouteImport.update({
  id: '/acquisition',
  path: '/acquisition',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RealisationsIndexRoute = RealisationsIndexRouteImport.update({
  id: '/realisations/',
  path: '/realisations/',
  getParentRoute: () => rootRouteImport,
} as any)
const OutilsIndexRoute = OutilsIndexRouteImport.update({
  id: '/outils/',
  path: '/outils/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const RealisationsSlugRoute = RealisationsSlugRouteImport.update({
  id: '/realisations/$slug',
  path: '/realisations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OutilsBudgetGoogleAdsArtisanRoute =
  OutilsBudgetGoogleAdsArtisanRouteImport.update({
    id: '/outils/budget-google-ads-artisan',
    path: '/outils/budget-google-ads-artisan',
    getParentRoute: () => rootRouteImport,
  } as any)
const OutilsAuditFicheGoogleRoute = OutilsAuditFicheGoogleRouteImport.update({
  id: '/outils/audit-fiche-google',
  path: '/outils/audit-fiche-google',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acquisition': typeof AcquisitionRoute
  '/agents-ia': typeof AgentsIaRoute
  '/application-web-mobile': typeof ApplicationWebMobileRoute
  '/automatisation-taches': typeof AutomatisationTachesRoute
  '/blog': typeof BlogRouteWithChildren
  '/cgv': typeof CgvRoute
  '/cookies': typeof CookiesRoute
  '/creation-site-internet': typeof CreationSiteInternetRoute
  '/crm-sur-mesure': typeof CrmSurMesureRoute
  '/integration-api': typeof IntegrationApiRoute
  '/landing-page': typeof LandingPageRoute
  '/logiciel-metier': typeof LogicielMetierRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/publicite-reseaux-sociaux': typeof PubliciteReseauxSociauxRoute
  '/referencement-ia': typeof ReferencementIaRoute
  '/referencement-local': typeof ReferencementLocalRoute
  '/referencement-naturel': typeof ReferencementNaturelRoute
  '/refonte-site-internet': typeof RefonteSiteInternetRoute
  '/site-e-commerce': typeof SiteECommerceRoute
  '/site-evenementiel': typeof SiteEvenementielRoute
  '/site-internet-carreleur': typeof SiteInternetCarreleurRoute
  '/site-internet-chauffagiste': typeof SiteInternetChauffagisteRoute
  '/site-internet-couvreur': typeof SiteInternetCouvreurRoute
  '/site-internet-electricien': typeof SiteInternetElectricienRoute
  '/site-internet-macon': typeof SiteInternetMaconRoute
  '/site-internet-menuisier': typeof SiteInternetMenuisierRoute
  '/site-internet-paysagiste': typeof SiteInternetPaysagisteRoute
  '/site-internet-peintre': typeof SiteInternetPeintreRoute
  '/site-internet-plombier': typeof SiteInternetPlombierRoute
  '/site-internet-serrurier': typeof SiteInternetSerrurierRoute
  '/site-vitrine': typeof SiteVitrineRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/outils/audit-fiche-google': typeof OutilsAuditFicheGoogleRoute
  '/outils/budget-google-ads-artisan': typeof OutilsBudgetGoogleAdsArtisanRoute
  '/realisations/$slug': typeof RealisationsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/outils/': typeof OutilsIndexRoute
  '/realisations/': typeof RealisationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acquisition': typeof AcquisitionRoute
  '/agents-ia': typeof AgentsIaRoute
  '/application-web-mobile': typeof ApplicationWebMobileRoute
  '/automatisation-taches': typeof AutomatisationTachesRoute
  '/cgv': typeof CgvRoute
  '/cookies': typeof CookiesRoute
  '/creation-site-internet': typeof CreationSiteInternetRoute
  '/crm-sur-mesure': typeof CrmSurMesureRoute
  '/integration-api': typeof IntegrationApiRoute
  '/landing-page': typeof LandingPageRoute
  '/logiciel-metier': typeof LogicielMetierRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/publicite-reseaux-sociaux': typeof PubliciteReseauxSociauxRoute
  '/referencement-ia': typeof ReferencementIaRoute
  '/referencement-local': typeof ReferencementLocalRoute
  '/referencement-naturel': typeof ReferencementNaturelRoute
  '/refonte-site-internet': typeof RefonteSiteInternetRoute
  '/site-e-commerce': typeof SiteECommerceRoute
  '/site-evenementiel': typeof SiteEvenementielRoute
  '/site-internet-carreleur': typeof SiteInternetCarreleurRoute
  '/site-internet-chauffagiste': typeof SiteInternetChauffagisteRoute
  '/site-internet-couvreur': typeof SiteInternetCouvreurRoute
  '/site-internet-electricien': typeof SiteInternetElectricienRoute
  '/site-internet-macon': typeof SiteInternetMaconRoute
  '/site-internet-menuisier': typeof SiteInternetMenuisierRoute
  '/site-internet-paysagiste': typeof SiteInternetPaysagisteRoute
  '/site-internet-peintre': typeof SiteInternetPeintreRoute
  '/site-internet-plombier': typeof SiteInternetPlombierRoute
  '/site-internet-serrurier': typeof SiteInternetSerrurierRoute
  '/site-vitrine': typeof SiteVitrineRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/outils/audit-fiche-google': typeof OutilsAuditFicheGoogleRoute
  '/outils/budget-google-ads-artisan': typeof OutilsBudgetGoogleAdsArtisanRoute
  '/realisations/$slug': typeof RealisationsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/outils': typeof OutilsIndexRoute
  '/realisations': typeof RealisationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acquisition': typeof AcquisitionRoute
  '/agents-ia': typeof AgentsIaRoute
  '/application-web-mobile': typeof ApplicationWebMobileRoute
  '/automatisation-taches': typeof AutomatisationTachesRoute
  '/blog': typeof BlogRouteWithChildren
  '/cgv': typeof CgvRoute
  '/cookies': typeof CookiesRoute
  '/creation-site-internet': typeof CreationSiteInternetRoute
  '/crm-sur-mesure': typeof CrmSurMesureRoute
  '/integration-api': typeof IntegrationApiRoute
  '/landing-page': typeof LandingPageRoute
  '/logiciel-metier': typeof LogicielMetierRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/publicite-reseaux-sociaux': typeof PubliciteReseauxSociauxRoute
  '/referencement-ia': typeof ReferencementIaRoute
  '/referencement-local': typeof ReferencementLocalRoute
  '/referencement-naturel': typeof ReferencementNaturelRoute
  '/refonte-site-internet': typeof RefonteSiteInternetRoute
  '/site-e-commerce': typeof SiteECommerceRoute
  '/site-evenementiel': typeof SiteEvenementielRoute
  '/site-internet-carreleur': typeof SiteInternetCarreleurRoute
  '/site-internet-chauffagiste': typeof SiteInternetChauffagisteRoute
  '/site-internet-couvreur': typeof SiteInternetCouvreurRoute
  '/site-internet-electricien': typeof SiteInternetElectricienRoute
  '/site-internet-macon': typeof SiteInternetMaconRoute
  '/site-internet-menuisier': typeof SiteInternetMenuisierRoute
  '/site-internet-paysagiste': typeof SiteInternetPaysagisteRoute
  '/site-internet-peintre': typeof SiteInternetPeintreRoute
  '/site-internet-plombier': typeof SiteInternetPlombierRoute
  '/site-internet-serrurier': typeof SiteInternetSerrurierRoute
  '/site-vitrine': typeof SiteVitrineRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/outils/audit-fiche-google': typeof OutilsAuditFicheGoogleRoute
  '/outils/budget-google-ads-artisan': typeof OutilsBudgetGoogleAdsArtisanRoute
  '/realisations/$slug': typeof RealisationsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/outils/': typeof OutilsIndexRoute
  '/realisations/': typeof RealisationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acquisition'
    | '/agents-ia'
    | '/application-web-mobile'
    | '/automatisation-taches'
    | '/blog'
    | '/cgv'
    | '/cookies'
    | '/creation-site-internet'
    | '/crm-sur-mesure'
    | '/integration-api'
    | '/landing-page'
    | '/logiciel-metier'
    | '/mentions-legales'
    | '/politique-confidentialite'
    | '/publicite-reseaux-sociaux'
    | '/referencement-ia'
    | '/referencement-local'
    | '/referencement-naturel'
    | '/refonte-site-internet'
    | '/site-e-commerce'
    | '/site-evenementiel'
    | '/site-internet-carreleur'
    | '/site-internet-chauffagiste'
    | '/site-internet-couvreur'
    | '/site-internet-electricien'
    | '/site-internet-macon'
    | '/site-internet-menuisier'
    | '/site-internet-paysagiste'
    | '/site-internet-peintre'
    | '/site-internet-plombier'
    | '/site-internet-serrurier'
    | '/site-vitrine'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/outils/audit-fiche-google'
    | '/outils/budget-google-ads-artisan'
    | '/realisations/$slug'
    | '/blog/'
    | '/outils/'
    | '/realisations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acquisition'
    | '/agents-ia'
    | '/application-web-mobile'
    | '/automatisation-taches'
    | '/cgv'
    | '/cookies'
    | '/creation-site-internet'
    | '/crm-sur-mesure'
    | '/integration-api'
    | '/landing-page'
    | '/logiciel-metier'
    | '/mentions-legales'
    | '/politique-confidentialite'
    | '/publicite-reseaux-sociaux'
    | '/referencement-ia'
    | '/referencement-local'
    | '/referencement-naturel'
    | '/refonte-site-internet'
    | '/site-e-commerce'
    | '/site-evenementiel'
    | '/site-internet-carreleur'
    | '/site-internet-chauffagiste'
    | '/site-internet-couvreur'
    | '/site-internet-electricien'
    | '/site-internet-macon'
    | '/site-internet-menuisier'
    | '/site-internet-paysagiste'
    | '/site-internet-peintre'
    | '/site-internet-plombier'
    | '/site-internet-serrurier'
    | '/site-vitrine'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/outils/audit-fiche-google'
    | '/outils/budget-google-ads-artisan'
    | '/realisations/$slug'
    | '/blog'
    | '/outils'
    | '/realisations'
  id:
    | '__root__'
    | '/'
    | '/acquisition'
    | '/agents-ia'
    | '/application-web-mobile'
    | '/automatisation-taches'
    | '/blog'
    | '/cgv'
    | '/cookies'
    | '/creation-site-internet'
    | '/crm-sur-mesure'
    | '/integration-api'
    | '/landing-page'
    | '/logiciel-metier'
    | '/mentions-legales'
    | '/politique-confidentialite'
    | '/publicite-reseaux-sociaux'
    | '/referencement-ia'
    | '/referencement-local'
    | '/referencement-naturel'
    | '/refonte-site-internet'
    | '/site-e-commerce'
    | '/site-evenementiel'
    | '/site-internet-carreleur'
    | '/site-internet-chauffagiste'
    | '/site-internet-couvreur'
    | '/site-internet-electricien'
    | '/site-internet-macon'
    | '/site-internet-menuisier'
    | '/site-internet-paysagiste'
    | '/site-internet-peintre'
    | '/site-internet-plombier'
    | '/site-internet-serrurier'
    | '/site-vitrine'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/outils/audit-fiche-google'
    | '/outils/budget-google-ads-artisan'
    | '/realisations/$slug'
    | '/blog/'
    | '/outils/'
    | '/realisations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcquisitionRoute: typeof AcquisitionRoute
  AgentsIaRoute: typeof AgentsIaRoute
  ApplicationWebMobileRoute: typeof ApplicationWebMobileRoute
  AutomatisationTachesRoute: typeof AutomatisationTachesRoute
  BlogRoute: typeof BlogRouteWithChildren
  CgvRoute: typeof CgvRoute
  CookiesRoute: typeof CookiesRoute
  CreationSiteInternetRoute: typeof CreationSiteInternetRoute
  CrmSurMesureRoute: typeof CrmSurMesureRoute
  IntegrationApiRoute: typeof IntegrationApiRoute
  LandingPageRoute: typeof LandingPageRoute
  LogicielMetierRoute: typeof LogicielMetierRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PolitiqueConfidentialiteRoute: typeof PolitiqueConfidentialiteRoute
  PubliciteReseauxSociauxRoute: typeof PubliciteReseauxSociauxRoute
  ReferencementIaRoute: typeof ReferencementIaRoute
  ReferencementLocalRoute: typeof ReferencementLocalRoute
  ReferencementNaturelRoute: typeof ReferencementNaturelRoute
  RefonteSiteInternetRoute: typeof RefonteSiteInternetRoute
  SiteECommerceRoute: typeof SiteECommerceRoute
  SiteEvenementielRoute: typeof SiteEvenementielRoute
  SiteInternetCarreleurRoute: typeof SiteInternetCarreleurRoute
  SiteInternetChauffagisteRoute: typeof SiteInternetChauffagisteRoute
  SiteInternetCouvreurRoute: typeof SiteInternetCouvreurRoute
  SiteInternetElectricienRoute: typeof SiteInternetElectricienRoute
  SiteInternetMaconRoute: typeof SiteInternetMaconRoute
  SiteInternetMenuisierRoute: typeof SiteInternetMenuisierRoute
  SiteInternetPaysagisteRoute: typeof SiteInternetPaysagisteRoute
  SiteInternetPeintreRoute: typeof SiteInternetPeintreRoute
  SiteInternetPlombierRoute: typeof SiteInternetPlombierRoute
  SiteInternetSerrurierRoute: typeof SiteInternetSerrurierRoute
  SiteVitrineRoute: typeof SiteVitrineRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  OutilsAuditFicheGoogleRoute: typeof OutilsAuditFicheGoogleRoute
  OutilsBudgetGoogleAdsArtisanRoute: typeof OutilsBudgetGoogleAdsArtisanRoute
  RealisationsSlugRoute: typeof RealisationsSlugRoute
  OutilsIndexRoute: typeof OutilsIndexRoute
  RealisationsIndexRoute: typeof RealisationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-vitrine': {
      id: '/site-vitrine'
      path: '/site-vitrine'
      fullPath: '/site-vitrine'
      preLoaderRoute: typeof SiteVitrineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-internet-serrurier': {
      id: '/site-internet-serrurier'
      path: '/site-internet-serrurier'
      fullPath: '/site-internet-serrurier'
      preLoaderRoute: typeof SiteInternetSerrurierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-internet-plombier': {
      id: '/site-internet-plombier'
      path: '/site-internet-plombier'
      fullPath: '/site-internet-plombier'
      preLoaderRoute: typeof SiteInternetPlombierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-internet-peintre': {
      id: '/site-internet-peintre'
      path: '/site-internet-peintre'
      fullPath: '/site-internet-peintre'
      preLoaderRoute: typeof SiteInternetPeintreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-internet-paysagiste': {
      id: '/site-internet-paysagiste'
      path: '/site-internet-paysagiste'
      fullPath: '/site-internet-paysagiste'
      preLoaderRoute: typeof SiteInternetPaysagisteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-internet-menuisier': {
      id: '/site-internet-menuisier'
      path: '/site-internet-menuisier'
      fullPath: '/site-internet-menuisier'
      preLoaderRoute: typeof SiteInternetMenuisierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-internet-macon': {
      id: '/site-internet-macon'
      path: '/site-internet-macon'
      fullPath: '/site-internet-macon'
      preLoaderRoute: typeof SiteInternetMaconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-internet-electricien': {
      id: '/site-internet-electricien'
      path: '/site-internet-electricien'
      fullPath: '/site-internet-electricien'
      preLoaderRoute: typeof SiteInternetElectricienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-internet-couvreur': {
      id: '/site-internet-couvreur'
      path: '/site-internet-couvreur'
      fullPath: '/site-internet-couvreur'
      preLoaderRoute: typeof SiteInternetCouvreurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-internet-chauffagiste': {
      id: '/site-internet-chauffagiste'
      path: '/site-internet-chauffagiste'
      fullPath: '/site-internet-chauffagiste'
      preLoaderRoute: typeof SiteInternetChauffagisteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-internet-carreleur': {
      id: '/site-internet-carreleur'
      path: '/site-internet-carreleur'
      fullPath: '/site-internet-carreleur'
      preLoaderRoute: typeof SiteInternetCarreleurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-evenementiel': {
      id: '/site-evenementiel'
      path: '/site-evenementiel'
      fullPath: '/site-evenementiel'
      preLoaderRoute: typeof SiteEvenementielRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-e-commerce': {
      id: '/site-e-commerce'
      path: '/site-e-commerce'
      fullPath: '/site-e-commerce'
      preLoaderRoute: typeof SiteECommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refonte-site-internet': {
      id: '/refonte-site-internet'
      path: '/refonte-site-internet'
      fullPath: '/refonte-site-internet'
      preLoaderRoute: typeof RefonteSiteInternetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referencement-naturel': {
      id: '/referencement-naturel'
      path: '/referencement-naturel'
      fullPath: '/referencement-naturel'
      preLoaderRoute: typeof ReferencementNaturelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referencement-local': {
      id: '/referencement-local'
      path: '/referencement-local'
      fullPath: '/referencement-local'
      preLoaderRoute: typeof ReferencementLocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referencement-ia': {
      id: '/referencement-ia'
      path: '/referencement-ia'
      fullPath: '/referencement-ia'
      preLoaderRoute: typeof ReferencementIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicite-reseaux-sociaux': {
      id: '/publicite-reseaux-sociaux'
      path: '/publicite-reseaux-sociaux'
      fullPath: '/publicite-reseaux-sociaux'
      preLoaderRoute: typeof PubliciteReseauxSociauxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-confidentialite': {
      id: '/politique-confidentialite'
      path: '/politique-confidentialite'
      fullPath: '/politique-confidentialite'
      preLoaderRoute: typeof PolitiqueConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logiciel-metier': {
      id: '/logiciel-metier'
      path: '/logiciel-metier'
      fullPath: '/logiciel-metier'
      preLoaderRoute: typeof LogicielMetierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing-page': {
      id: '/landing-page'
      path: '/landing-page'
      fullPath: '/landing-page'
      preLoaderRoute: typeof LandingPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration-api': {
      id: '/integration-api'
      path: '/integration-api'
      fullPath: '/integration-api'
      preLoaderRoute: typeof IntegrationApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm-sur-mesure': {
      id: '/crm-sur-mesure'
      path: '/crm-sur-mesure'
      fullPath: '/crm-sur-mesure'
      preLoaderRoute: typeof CrmSurMesureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creation-site-internet': {
      id: '/creation-site-internet'
      path: '/creation-site-internet'
      fullPath: '/creation-site-internet'
      preLoaderRoute: typeof CreationSiteInternetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automatisation-taches': {
      id: '/automatisation-taches'
      path: '/automatisation-taches'
      fullPath: '/automatisation-taches'
      preLoaderRoute: typeof AutomatisationTachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application-web-mobile': {
      id: '/application-web-mobile'
      path: '/application-web-mobile'
      fullPath: '/application-web-mobile'
      preLoaderRoute: typeof ApplicationWebMobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents-ia': {
      id: '/agents-ia'
      path: '/agents-ia'
      fullPath: '/agents-ia'
      preLoaderRoute: typeof AgentsIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acquisition': {
      id: '/acquisition'
      path: '/acquisition'
      fullPath: '/acquisition'
      preLoaderRoute: typeof AcquisitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realisations/': {
      id: '/realisations/'
      path: '/realisations'
      fullPath: '/realisations/'
      preLoaderRoute: typeof RealisationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outils/': {
      id: '/outils/'
      path: '/outils'
      fullPath: '/outils/'
      preLoaderRoute: typeof OutilsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/realisations/$slug': {
      id: '/realisations/$slug'
      path: '/realisations/$slug'
      fullPath: '/realisations/$slug'
      preLoaderRoute: typeof RealisationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outils/budget-google-ads-artisan': {
      id: '/outils/budget-google-ads-artisan'
      path: '/outils/budget-google-ads-artisan'
      fullPath: '/outils/budget-google-ads-artisan'
      preLoaderRoute: typeof OutilsBudgetGoogleAdsArtisanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outils/audit-fiche-google': {
      id: '/outils/audit-fiche-google'
      path: '/outils/audit-fiche-google'
      fullPath: '/outils/audit-fiche-google'
      preLoaderRoute: typeof OutilsAuditFicheGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcquisitionRoute: AcquisitionRoute,
  AgentsIaRoute: AgentsIaRoute,
  ApplicationWebMobileRoute: ApplicationWebMobileRoute,
  AutomatisationTachesRoute: AutomatisationTachesRoute,
  BlogRoute: BlogRouteWithChildren,
  CgvRoute: CgvRoute,
  CookiesRoute: CookiesRoute,
  CreationSiteInternetRoute: CreationSiteInternetRoute,
  CrmSurMesureRoute: CrmSurMesureRoute,
  IntegrationApiRoute: IntegrationApiRoute,
  LandingPageRoute: LandingPageRoute,
  LogicielMetierRoute: LogicielMetierRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PolitiqueConfidentialiteRoute: PolitiqueConfidentialiteRoute,
  PubliciteReseauxSociauxRoute: PubliciteReseauxSociauxRoute,
  ReferencementIaRoute: ReferencementIaRoute,
  ReferencementLocalRoute: ReferencementLocalRoute,
  ReferencementNaturelRoute: ReferencementNaturelRoute,
  RefonteSiteInternetRoute: RefonteSiteInternetRoute,
  SiteECommerceRoute: SiteECommerceRoute,
  SiteEvenementielRoute: SiteEvenementielRoute,
  SiteInternetCarreleurRoute: SiteInternetCarreleurRoute,
  SiteInternetChauffagisteRoute: SiteInternetChauffagisteRoute,
  SiteInternetCouvreurRoute: SiteInternetCouvreurRoute,
  SiteInternetElectricienRoute: SiteInternetElectricienRoute,
  SiteInternetMaconRoute: SiteInternetMaconRoute,
  SiteInternetMenuisierRoute: SiteInternetMenuisierRoute,
  SiteInternetPaysagisteRoute: SiteInternetPaysagisteRoute,
  SiteInternetPeintreRoute: SiteInternetPeintreRoute,
  SiteInternetPlombierRoute: SiteInternetPlombierRoute,
  SiteInternetSerrurierRoute: SiteInternetSerrurierRoute,
  SiteVitrineRoute: SiteVitrineRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  OutilsAuditFicheGoogleRoute: OutilsAuditFicheGoogleRoute,
  OutilsBudgetGoogleAdsArtisanRoute: OutilsBudgetGoogleAdsArtisanRoute,
  RealisationsSlugRoute: RealisationsSlugRoute,
  OutilsIndexRoute: OutilsIndexRoute,
  RealisationsIndexRoute: RealisationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
